"use client";

import { FormEvent, useState } from "react";

type UserRow = { id: string; email: string; balance: number; created_at: string; last_sign_in_at: string | null };
type Transaction = { id: string; user_id: string; type: string; amount: number; description: string | null; created_at: string };

export default function AdminCreditManager({ initialUsers, initialTransactions }: { initialUsers: UserRow[]; initialTransactions: Transaction[] }) {
  const [users, setUsers] = useState<UserRow[]>(initialUsers); const [transactions, setTransactions] = useState<Transaction[]>(initialTransactions);
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState(""); const [amount, setAmount] = useState(1); const [description, setDescription] = useState("Admin testing credit"); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  async function load(search = "") { const response = await fetch(`/api/admin/users?q=${encodeURIComponent(search)}`); const body = await response.json(); if (!response.ok) return setError(body.error); setUsers(body.users); setTransactions(body.transactions); }
  async function adjust(event: FormEvent) { event.preventDefault(); setError(""); setNotice(""); const response = await fetch("/api/admin/credits", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: selected, amount, description }) }); const body = await response.json(); if (!response.ok) return setError(body.error || "Unable to adjust credits"); setNotice(`Balance updated to ${body.balance}.`); await load(query); }
  return <><form className="admin-form" onSubmit={adjust}><section className="admin-form-section"><h2>Manual contact credit adjustment</h2><div className="admin-fields"><label className="admin-field full">Find user<div className="admin-actions"><input value={query} placeholder="Search by email" onChange={(event) => setQuery(event.target.value)} /><button type="button" className="admin-secondary" onClick={() => load(query)}>Search</button></div></label><label className="admin-field">User<select required value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Select a user</option>{users.map((user) => <option value={user.id} key={user.id}>{user.email} — {user.balance} credits</option>)}</select></label><label className="admin-field">Amount<input required type="number" value={amount} onChange={(event) => setAmount(Number(event.target.value))} /></label><label className="admin-field full">Audit reason<input required value={description} onChange={(event) => setDescription(event.target.value)} /></label></div></section>{error && <p className="admin-error">{error}</p>}{notice && <p className="admin-notice">{notice}</p>}<button className="admin-primary">Apply adjustment</button></form><div className="admin-panel"><h2>Recent credit ledger</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Type</th><th>Amount</th><th>Reason</th><th>Date</th></tr></thead><tbody>{transactions.map((row) => <tr key={row.id}><td>{users.find((user) => user.id === row.user_id)?.email ?? row.user_id}</td><td>{row.type}</td><td>{row.amount > 0 ? "+" : ""}{row.amount}</td><td>{row.description || "—"}</td><td>{new Date(row.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></div></>;
}
